name: CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Copy to EC2
      uses: appleboy/scp-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_KEY }}
        source: "./*"
        target: /var/www/mywebsite/ecommerce-app

    - name: Run app with PM2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd /var/www/mywebsite/ecommerce-app
          npm install
<<<<<<< HEAD
          pm2 start server.js --name "ecommerce-app" -f
          pm2 save
=======
          pm2 start server.js --name "ecommerce-app"
          pm2 save
          pm2 startup systemd
>>>>>>> 3d93d74a2b90205894121d8fd89dbd18ed49a6fb
